spring:
  application:
    name: spring-ldap
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2-database/spring-security-db
    username: abdul-razak
    password: 206207
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
